# Generated by Django 5.2 on 2025-04-23 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'Other')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
